import Head from 'next/head';
import * as React from 'react';
import Album from '@/components/Landing';

const Home = () => {
  return (
    <>
      <Head>
        <title>CloudCast</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Album />
      </main>
    </>
  );
};

export default Home;
